---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(janitor)

```

```{r}
birth_weight_summary %>% 
  arrange(start_year)
```



```{r}
birth_weight_summary <- 
birth_weight_summary %>% 
  mutate(middle_year = start_year + 1)


birth_weight_summary <- 
birth_weight_summary[, c(1, 9, 14, 10, 8, 12, 13, 2, 3, 4, 5, 6, 7, 11)]
  
  
  birth_weight_summary
  
  #so I'm looking for a way to plot all instances of low birth weight per year. First thing I've done is create a column with the middle year, so all years are represented and not just the first and last. Now, I need to find a way to add up all instances of low weight births as they happen in EACH year... so I want the same low weight births recorded three times for 2014, once for the start year, once for the middle year, and once for the end year. My hypothesis is that this will weight count in favour of years which are counted fully in the data, and help my isolate the ones which are only represented once, in the end or start year (so the year 2012 for start, 2016 for end).
  
  #trialling with smaller dataset first
  
  birth_weight_summary %>% 
  filter(date_code == "2012-2014" | date_code == "2013-2015" | date_code == "2014-2016",
         data_zone_name == "Doon Valley South - 01") %>% 
    mutate(average_per_year_)

```




```{r}
birth_weight_summary <- 
birth_weight_summary %>% 
  mutate(second_year = start_year + 1)


birth_weight_summary <- 
birth_weight_summary[, c(1, 9, 14, 10, 8, 12, 13, 2, 3, 4, 5, 6, 7, 11)]
  
  
  birth_weight_summary
  
  #so I'm looking for a way to plot all instances of low birth weight per year. First thing I've done is create a column with the middle year, so all years are represented and not just the first and last. Now, I need to find a way to add up all instances of low weight births as they happen in EACH year... so I want the same low weight births recorded three times for 2014, once for the start year, once for the middle year, and once for the end year. My hypothesis is that this will weight count in favour of years which are counted fully in the data, and help my isolate the ones which are only represented once, in the end or start year (so the year 2012 for start, 2016 for end).
  
  #trialling with smaller dataset first
  
  birth_weight_summary %>% 
  filter(date_code == "2012-2014" | date_code == "2013-2015" | date_code == "2014-2016",
         data_zone_name == "Doon Valley South - 01") %>% 
    mutate(average_per_year_)
```


detail contained in short decription or another tab, more intersted in broader view and how issue related to scottish public health in general. broad but not too broa, better than trying to hone in on one magic number.



```{r}
birth_weight_summary
```

```{r}
raw_birth_weight <- 
  read_csv("raw_data/birth_weight.csv") %>% 
  clean_names()

raw_birth_weight %>%
  filter(birth_weight == "Low Weight Births") %>% 
  dplyr::select(-measurement) %>% 
  pivot_wider(names_from = units,
              values_from = value) %>% 
  clean_names() %>% 
  dplyr::filter(births == 0,
                percent_of_births > 0)






raw_birth_weight %>% 
  filter(FeatureCode == "S92000003",
         Units == "Percent Of Births") %>% 
  arrange(desc(DateCode))
```

```{r}
appropriate_age <-

read_csv("raw_data/Appropriate Birthweight for Gestational Age.csv") %>% 
  clean_names()

appropriate_age
```


```{r}
read_csv("raw_data/12.2_birthweight.csv") %>% 
  arrange(desc(SIMDVersion))

#Data on the appropriateness of birthweights for gestational age at birth. It is important to be able to differentiate between babies who are light because they are preterm and those who are inappropriately light after adjustment for gestational age at birth.

#Babies identify as appropriate weight for gestational age with a birthweight between the 5th and 95th percentiles. Babies identified as small or large for gestational age are those whose birthweight is under the 5th or over the 95th percentile respectively.


```




```{r}
library(xlsx)
```


```{r}

birth_weight_scotland <-
  readxl::read_xlsx("raw_data/tables_on_birth_weight.xlsx", sheet = "Table8.1") %>% 
  slice(6:20000) %>% 
  janitor::row_to_names(1) %>% 
  clean_names()


lbw_maternal_age <-
  readxl::read_xlsx("raw_data/tables_on_birth_weight.xlsx", sheet = "Table8.2")  %>% 
  slice(6:20000) %>% 
  janitor::row_to_names(1) %>% 
  clean_names()


lbw_deprivation_category <-
  readxl::read_xlsx("raw_data/tables_on_birth_weight.xlsx", sheet = "Table8.3")  %>% 
  slice(6:20000) %>% 
  janitor::row_to_names(1) %>% 
  clean_names()


lbw_nhs_board_of_residence <-
readxl::read_xlsx("raw_data/tables_on_birth_weight.xlsx", sheet = "Table8.4")  %>% 
  slice(6:20000) %>% 
  janitor::row_to_names(1) %>% 
  clean_names()


lbw_local_authority_of_residence <-
readxl::read_xlsx("raw_data/tables_on_birth_weight.xlsx", sheet = "Table8.5")  %>% 
  slice(6:20000) %>% 
  janitor::row_to_names(1) %>% 
  clean_names()


birth_weight_scotland
lbw_maternal_age
lbw_deprivation_category
lbw_nhs_board_of_residence
lbw_local_authority_of_residence


```

```{r}
birth_weight_scotland <-
birth_weight_scotland  %>% 
  mutate(x1500_below_count = as.numeric(x1500g),
         x1500_to_2499_count = as.numeric(x1500_2499g),
         x2500_to_3999_count = as.numeric(x2500_3999g),
         x4000_above_count = as.numeric(x4000g),
         
         x1500_below_percent = as.numeric(x1500g_2),
         x1500_to_2499_percent = as.numeric(x1500_2499g_2),
         x2500_to_3999_percent = as.numeric(x2500_3999g_2),
         x4000_above_percent = as.numeric(x4000g_2),) 

birth_weight_scotland



birth_weight_scotland_percent <- 
  birth_weight_scotland %>% 
  select(year, x1500_below_percent:x4000_above_percent) %>% 
  slice(30:44)

birth_weight_scotland_percent
  birth_weight_scotland
         
lbw_maternal_age
lbw_deprivation_category


lbw_nhs_board_of_residence <-
lbw_nhs_board_of_residence %>% 
  mutate(x1500_below_count = as.numeric(x1500g),
         x1500_to_2499_count = as.numeric(x1500_2499g),
         x2500_to_3999_count = as.numeric(x2500_3999g),
         x4000_above_count = as.numeric(x4000g),
         
         x1500_below_percent = as.numeric(x1500g_2),
         x1500_to_2499_percent = as.numeric(x1500_2499g_2),
         x2500_to_3999_percent = as.numeric(x2500_3999g_2),
         x4000_above_percent = as.numeric(x4000g_2),) %>% 
  select(nhs_board_of_residence, x1500_below_percent:x4000_above_percent) 

left_join(lbw_nhs_board_of_residence, birth_weight_scotland, by = c()

birth_weight_summary

lbw_nhs_board_of_residence
```

```{r}
#appropriate_age <-

appropriate_age <-
read_csv("raw_data/Appropriate Birthweight for Gestational Age.csv") %>% 
  clean_names()



appropriate_age <-
appropriate_age %>% 
  select(-id) %>% 
  separate(financial_year, into = c("financial_year", "end_year"), sep = "/", convert = TRUE) %>% 
  select(-end_year) %>% 
  mutate(financial_year = as.numeric(financial_year),
         council_area_code = ca) %>% 
  select(-simd_quintile_qf) %>% 
  filter(financial_year >= 2012,
         ca != "RA2704")

inner_join(appropriate_age, birth_weight_summary, by = c("council_area_code" = "la_code"))
  

birth_weight_summary
appropriate_age
```




















